sudo: required
services:
  - docker

before_install:
  - docker build -t arcseldon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arcseldon/react-test npm test

after_success:
  - docker build -t arcseldon/multi-client ./client
  - docker build -t arcseldon/multi-nginx ./nginx
  - docker build -t arcseldon/multi-server ./server
  - docker build -t arcseldon/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push arcseldon/multi-client
  - docker push arcseldon/multi-nginx
  - docker push arcseldon/multi-server
  - docker push arcseldon/multi-worker


deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-270669780448"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
